spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:jwtoken
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate ??? ?? data.sql ??

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secretKey: 6/XhJr9v+SVANc/Uj0H8I15S7JY8If0QqpEqFIFFeM8=
  access:
    expired: 600000
  refresh:
    expired: 10080000

kakao:
  api_key: a521a7765e4b1eabca44928d9fc4e13b
  redirect_uri: http://localhost:8080/v1/login/kakao
  token_uri: https://kauth.kakao.com/oauth/token
  info_uri : https://kapi.kakao.com/v2/user/me


